# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6a16577917c03ccb9b0becab54e7e38ec0d733dd6b8a64cd7baabde8fe63940cd94f281de865f7f637d94689aabd7bb60b4aeb699afe93c520b04d71ef16140c

test:
  secret_key_base: 25b172aad0406c817b61cfa470c8f23e65814e9b884f5a4762b1e4af0d216e9c4e126bb46faa9ef7f502039e99189f0bb3bfab4a5c38b0484b59682c18065589

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
